import test from 'node:test';import assert from 'node:assert/strict';import {createWorker} from './index.js';
const ID='typo_f904cbe7-12ef-4ce1-a6ac-37e16d7c009c',actor='user-visual-test';
const legacy={schema:'isolated-typography-delivery/v2',task_id:ID,request_key:'dituyiwai_typography_v020_20261007',request_title:'地图以外·独立可编辑文字设计',reference_source:'sediment://file_000000005b5c82088178c780dff69ff9',revision:6,status:'IN_PROGRESS',stage:'ACTUAL_INDEPENDENT_TYPOGRAPHY_REVIEW',next_required_action:'ACTUAL_INDEPENDENT_TYPOGRAPHY_REVIEW',requested_copy:{main_wordmark:'地图以外',top_wordmark:'地图以外',english:'for liuxiansheng',vertical_copy:'不是所有远方，都写在地图上',footer_copy:'离开既定路线，去看未知远方'},native_snapshot:{source:{commit:'d'.repeat(40)},stage:'S7_UNCHANGED',snapshot_only:true},latest_artifacts:{LOCAL_LETTERING_ASSET:{asset_type:'guide-only'}},artifact_history:[{revision:2,stage:'REFERENCE_TEXT_EXTRACTION'}],created_at:'2026-10-07T07:42:40.409Z',updated_at:'2026-10-07T08:22:12.660Z'};
function fakeDb(){let task=structuredClone(legacy);return {get:()=>task,prepare(sql){let params=[];return {bind(...args){params=args;return this;},async run(){if(sql.startsWith('UPDATE typography_delivery_tasks')){if(task.revision!==params[7])return {meta:{changes:0}};task=JSON.parse(params[3]);return {meta:{changes:1}};}return {meta:{changes:1}};},async first(){if(!sql.includes('SELECT payload FROM typography_delivery_tasks'))return null;if(sql.includes('task_id=?'))return params[0]===actor&&params[1]===task.task_id?{payload:JSON.stringify(task)}:null;if(sql.includes('request_key=?'))return params[0]===actor&&params[1]===task.request_key?{payload:JSON.stringify(task)}:null;return {payload:JSON.stringify(task)};}};}};}
const env={DB:fakeDb()};const worker=createWorker({adapters:{resolveHead:async()=>'',readFile:async()=>new Uint8Array()},clock:()=> '2026-10-08T02:00:00Z'});
async function rpc(name,args={}){const req=new Request('https://example.chatgpt.site/mcp',{method:'POST',headers:{'content-type':'application/json','oai-authenticated-user-id':actor},body:JSON.stringify({jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}})});const res=await worker.fetch(req,env);return {status:res.status,body:await res.json()};}
test('root route keeps same site name and advances only contract version',async()=>{const res=await worker.fetch(new Request('https://example.chatgpt.site/'),env);const root=await res.json();assert.equal(root.version,'0.3.0');assert.equal(root.name,'刘先生·视觉设计工作流');assert.match(root.workflow,/AI生成透明完整文字母版/);});
test('get legacy task does not quietly treat it as v3 complete',async()=>{const r=await rpc('get_typography_delivery',{task_id:ID});assert.equal(r.status,200);assert.equal(r.body.result.structuredContent.contract_upgrade_required,true);assert.equal(r.body.result.structuredContent.completion_claim_allowed,false);});
test('upgrade v2 explicitly in exact same D1 row preserving history',async()=>{const x=await rpc('upgrade_typography_contract',{task_id:ID,expected_revision:6,migration_reason:'user explicitly requested new AI-master-first fidelity'});assert.equal(x.status,200);const t=x.body.result.structuredContent.task;assert.equal(t.revision,7);assert.equal(t.task_id,ID);assert.equal(t.request_key,legacy.request_key);assert.equal(t.schema,'isolated-typography-delivery/v3');assert.equal(t.stage,'REFERENCE_TEXT_EXTRACTION');assert.equal(t.artifact_history.length,2);assert.deepEqual(t.native_snapshot,legacy.native_snapshot);assert.deepEqual(t.legacy_artifacts,legacy.latest_artifacts);});
test('v3 rejects stage skips without corrupting task',async()=>{const r=await rpc('record_typography_stage',{task_id:ID,expected_revision:7,stage:'AI_COMPLETE_TRANSPARENT_TYPOGRAPHY_MASTER',artifact:{artifact_type:'AI_COMPLETE_TRANSPARENT_TYPOGRAPHY_MASTER'}});assert.equal(r.status,200);assert.equal(r.body.result.isError,true);assert.match(r.body.result.content[0].text,/STAGE_ORDER_VIOLATION/);const t=(await rpc('get_typography_delivery',{task_id:ID})).body.result.structuredContent.task;assert.equal(t.revision,7);assert.equal(t.stage,'REFERENCE_TEXT_EXTRACTION');});
test('repeating migration is harmless business rejection not transport abort',async()=>{const r=await rpc('upgrade_typography_contract',{task_id:ID,expected_revision:7,migration_reason:'again'});assert.equal(r.status,200);assert.equal(r.body.result.isError,true);assert.match(r.body.result.content[0].text,/ALREADY_UPGRADED/);});
test('tools/list exposes native legacy tools plus v3 upgrade tool',async()=>{const req=new Request('https://example.chatgpt.site/mcp',{method:'POST',headers:{'content-type':'application/json','oai-authenticated-user-id':actor},body:JSON.stringify({jsonrpc:'2.0',id:2,method:'tools/list',params:{}})});const res=await worker.fetch(req,env);const data=await res.json();const names=data.result.tools.map(x=>x.name);assert.ok(names.includes('upgrade_typography_contract'));assert.ok(names.includes('get_current_workflow'));assert.ok(names.includes('compile_transfer_plan'));assert.ok(names.includes('get_typography_delivery'));assert.ok(names.includes('record_typography_stage'));});
