
const page=await figma.getNodeByIdAsync('412:2');await figma.setCurrentPageAsync(page);
const temp=figma.currentPage.children.find(n=>n.name==='S7_TEMPORARY_SVG_TRANSPORT_NO_ARTWORK');if(!temp)throw Error('Missing transport');const WORDMARK_SVG=temp.children.find(n=>n.name==='PART_0').characters+temp.children.find(n=>n.name==='PART_1').characters+temp.children.find(n=>n.name==='PART_2').characters+temp.children.find(n=>n.name==='PART_3').characters+temp.children.find(n=>n.name==='PART_4').characters+temp.children.find(n=>n.name==='PART_5').characters+temp.children.find(n=>n.name==='PART_6').characters;const transportNodes=[temp,...temp.findAll()].map(n=>n.id);
const name='LIUXIANSHENG_CONTENT_TRANSFER_S7_REFERENCE_GRAIN_REPAIR';
if(page.children.some(n=>n.name===name))throw Error('Already exists; inspect, never replay');
function fp(n){const a=[];function walk(x){let q={id:x.id,name:x.name,type:x.type};for(const k of ['x','y','width','height','visible','opacity','locked','fills','strokes','vectorPaths','characters','fontName','fontSize','relativeTransform']){if(k in x)q[k]=x[k];}a.push(q);if('children'in x)x.children.forEach(walk)}walk(n);const j=JSON.stringify(a);let h=2166136261;for(let i=0;i<j.length;i++){h^=j.charCodeAt(i);h=Math.imul(h,16777619)}return {fnv1a32:h>>>0,serialized_length:j.length,nodes:a.length}}
const protectedIds=['416:2','424:2','429:2','435:2','442:2','447:2','449:2'],before={};for(const id of protectedIds)before[id]=fp(await figma.getNodeByIdAsync(id));
if(WORDMARK_SVG.length!==236016)throw Error('Transport length differs');let svgH=2166136261;for(let i=0;i<WORDMARK_SVG.length;i++){svgH^=WORDMARK_SVG.charCodeAt(i);svgH=Math.imul(svgH,16777619)}if((svgH>>>0)!==2932184347)throw Error('Transport hash differs');
const source=await figma.getNodeByIdAsync('449:2');
const fonts=source.findAllWithCriteria({types:['TEXT']}).flatMap(t=>t.getStyledTextSegments(['fontName']).map(s=>s.fontName));
const unique=new Map(fonts.map(f=>[JSON.stringify(f),f]));await Promise.all([...unique.values()].map(f=>figma.loadFontAsync(f)));
const f=source.clone();f.name=name;page.appendChild(f);f.x=Math.max(...page.children.filter(n=>n.id!==f.id).map(n=>n.x+n.width),0)+160;f.y=source.y;
const old=f.children.find(n=>n.name==='WHOLE_STROKE_RESHAPING_AND_SOURCE_ALPHA_GRAIN_S6');if(!old)throw Error('Cloned wordmark missing');
const removedNodeIds=[old,...old.findAll()].map(n=>n.id),oldIndex=f.children.indexOf(old),ox=old.x,oy=old.y;
const w=figma.createNodeFromSvg(WORDMARK_SVG);f.insertChild(oldIndex,w);w.name='REFERENCE_DONOR_GRAIN_AND_LOCAL_FACET_REPAIR_S7';w.x=ox;w.y=oy;
if(Math.abs(w.width-960)>.01||Math.abs(w.height-1280)>.01)throw Error('Wordmark viewport differs; no scaling');old.remove();
const after={};for(const id of protectedIds){after[id]=fp(await figma.getNodeByIdAsync(id));if(JSON.stringify(before[id])!==JSON.stringify(after[id]))throw Error('Protected version changed '+id);}
const all=[f,...f.findAll()],ts=f.findAllWithCriteria({types:['TEXT']});
temp.remove();return {removedTransportNodeIds:transportNodes,transport_identity_verified:true,createdNodeIds:all.map(n=>n.id),removedTransientCloneNodeIds:removedNodeIds,mutatedExistingNodeIds:[],file_key:figma.fileKey,page_id:page.id,page_name:page.name,frame_id:f.id,frame_name:f.name,width:f.width,height:f.height,text_count:ts.length,candidate_texts:ts.map(t=>t.characters),fonts:ts.map(t=>({id:t.id,text:t.characters,font:t.fontName,size:t.fontSize,bounds:t.absoluteBoundingBox,segments:t.getStyledTextSegments(['fontName','fontSize']),visible:t.visible,locked:t.locked,hasMissingFont:t.hasMissingFont})),wordmark_node:w.id,wordmark_layer_opacities:w.findAllWithCriteria({types:['VECTOR']}).map(n=>({id:n.id,opacity:n.opacity,fills:n.fills})),wordmark_vector_count:w.findAllWithCriteria({types:['VECTOR']}).length,vector_count:f.findAllWithCriteria({types:['VECTOR']}).length,type_frame_image_paints:all.flatMap(n=>Array.isArray(n.fills)?n.fills:[]).filter(p=>p.type==='IMAGE').length,reconstruction_source_sha256:'9ef09dd1814343a938445227ce9a8906f0eb1ae4531a857baaba0720606aa558',before,after,protected_s2_unchanged:true,protected_transfer_s1_s2_s3_s4_s5_s6_unchanged:true};
