from pathlib import Path
import json,hashlib,datetime
root=Path(r"C:/Users/Administrator/OneDrive/文档/足球/shenmei-vpd-resume-20261006");out=root/".liu-visual-private/s7_fresh_entry"
p=out/"INDEPENDENT_TOOL_EVIDENCE.json";raw=json.loads(p.read_text(encoding="utf-8"))
removed=0
def redact(v):
    global removed
    if isinstance(v,list):return [redact(x) for x in v]
    if isinstance(v,dict):
        d={}
        for k,x in v.items():
            if k=="download_url":
                removed+=1;continue
            d[k]=redact(x)
        return d
    return v
safe=redact(raw)
safe["publication_sanitization"]={"download_url_fields_removed":removed,"no_authenticated_short_lived_urls_preserved":True,"not_provider_raw_response_byte_equivalence":True,"canonical_drive_urls_and_ids_retained":True,"actual_independent_byte_SHA256_evidence_retained":True}
p.write_text(json.dumps(safe,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
def read(n):return json.loads((out/n).read_text(encoding="utf-8"))
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
native=read("NATIVE_ENTRY_EVIDENCE.json");refs=read("NATIVE_REFERENCE_CHECK.json");reconcile=read("GIT_LF_REFERENCE_RECONCILIATION.json")
assets=read("ASSET_AND_DEPENDENCY_EVIDENCE.json");zipdata=read("ZIP_INPUT_VERIFICATION.json");tools=read("INDEPENDENT_TOOL_EVIDENCE.json");plugin=read("PLUGIN_ACTUAL_READ_ONLY_EVIDENCE.json");fonts=read("FIGMA_FONT_AVAILABILITY.json")
source=tools["figma_current_source"][0];photo=tools["figma_protected_photo"][0]
wordmark_vectors=[v for v in source["vectors"] if v["name"].startswith("S7_CREAM_") or v["name"].startswith("ORANGE_")]
protected=json.loads((root/"evidence/vpd/codex_takeover_20261003/liuxiansheng_content_transfer_20261005/FIGMA_PHOTO_PROTECTION_S7.json").read_text(encoding="utf-8"))
expected_photo=protected["after"]["photo"]
photo_keys=["id","locked","visible","relativeTransform","fills"]
photo_match={k:photo["photo"].get(k)==expected_photo.get(k)for k in photo_keys}
delivery=json.loads((root/native["transfer_delivery"]["path"]).read_text(encoding="utf-8"))
evidence=[]
for p in sorted(out.iterdir()):
    if p.is_file() and p.suffix in [".json",".py",".js"] and p.name not in ["FRESH_ENTRY_REPORT.json","seal_recovery_report.py"]:
        evidence.append({"path":".liu-visual-private/s7_fresh_entry/"+p.name,"sha256":sha(p),"bytes":p.stat().st_size})
result={
 "schema":"vpd-s7-fresh-entry-recovery/v1",
 "recorded_at":datetime.datetime.now(datetime.timezone.utc).isoformat(),
 "scope":"WORKING_TREE_RECOVERY",
 "result":"CURRENT_S7_ARTIFACT_AND_ENTRY_REUSE_VERIFIED_WITH_LIMITATIONS",
 "seal_status":"SEALED_AFTER_READ_ONLY_RECOVERY",
 "initial_material":"START_HERE.md in the named active checkout only",
 "context_boundary":{"same_machine_new_context_only":True,"root_chat_or_runtime_read":False,"other_workers_private_work_files_read":False,"parent_progress_messages_not_used_as_pass_evidence":True,"external_cold_aesthetic_review":False,"actual_model_or_effort_self_verified":False,"actual_model":None,"actual_effort":None},
 "business_authority":{"repository":native["repository"],"branch":native["branch"],"local_parent_HEAD":native["head"],"GitHub_published_current_state":False,"native_lock_revision":349,"checkpoint_sequence":371,"status":native["status"],"current_task_id":native["current_task_id"],"current_stage":native["current_stage"],"next_required_action":native["next_required_action"],"sole_business_state_writer":"ROOT_EXECUTOR_ONLY","native_three_file_hashes":native["native"],"raw_native_mirrors_match":native["mirror_checks"]["adapter_lock_hash"] and native["mirror_checks"]["checkpoint_lock_hash"] and native["mirror_checks"]["revision_mirrors_match"] and native["mirror_checks"]["status_mirrors_match"] and native["mirror_checks"]["next_action_mirrors_match"]},
 "entry_recovery":{"route":["START_HERE.md","PROJECT_CONTROL_ADAPTER.json task_lock/workflow","VPD_PROJECT_ROADMAP.md and locked mainline/contract","CURRENT_TASK_LOCK.json","LATEST_CHECKPOINT.json","WORKER_CURRENT_REUSE.md","current codex_takeover receipt","content_transfer_experiment.delivery -> DELIVERY_MANIFEST_S7.json","METHODS_AND_REUSE_S7.md and SOURCE/DEPENDENCIES/REUSE_METHOD"],
 "entry_read_hashes":native["entry_read_hashes"],"latest_receipt_hash_match":native["mirror_checks"]["receipt_sha_matches"],"latest_delivery_hash_match":native["mirror_checks"]["current_delivery_sha_matches"],"reference_count":native["reference_summary"]["total_unique"],"all_reference_files_exist":all(r["exists"]for r in refs),"public_reference_raw_hash_matches":1621,"public_reference_LF_Git_blob_matches":4,"unexplained_public_reference_hash_mismatches":0,"private_or_runtime_references_existence_only":72,"LF_reconciliation":reconcile,
 "expected_public_report_at_snapshot":native["expected_public_fresh_entry_report"],
 "entry_ambiguities":[{"field":"WORKER_CURRENT_REUSE.md historical body","observation":"Large V29/history and S4 checkout-recovery text remain; only current native lock/receipt is used for S7 and next action."},{"field":"DELIVERY_MANIFEST_S7.json professional_scope_result","value":delivery["professional_scope_result"],"observation":"Stale S6/S7-not-reviewed wording remains alongside current professional_review reference. Read referenced FINAL_PROFESSIONAL_REVIEW.json (PASS, implementation/protocol/delivery only), and final s7_final_verified_review, rather than this old summary."}]},
 "mainline_and_protection":{"objective":native["objective"],"fixed_sequence":"complete poster -> content -> aspect -> second style -> fixed delivery; current local typography trial does not promote this sequence","frozen_photography_SHA256":native["frozen_source"]["sha256"],"tea_V29_and_photography_unchanged_by_this_reader":True,"tea_formal_versions":29,"tea_revisions":28,"current_transfer_versions":7,"cumulative_guide_calls":2,"old_failures_and_human_rejections_preserved_as_scoped_history":True,"human_acceptance":"PENDING","no_next_artwork_authorization_inferred":True,"current_unique_next_action":"LIU_REVIEW_LIUXIANSHENG_CONTENT_TRANSFER"},
 "current_artwork":{"final_drive_id":"1svX-5kyxGBA-hEKg6iq_xMaxcwYU0Ubt","final_drive_url":"https://drive.google.com/file/d/1svX-5kyxGBA-hEKg6iq_xMaxcwYU0Ubt/view","original_PNG":assets["pixel_identity"],"wordmark_drive_id":"15COp7aWZ7sKWKDinV3KasEQ38lVzt0e5","wordmark_drive_url":"https://drive.google.com/file/d/15COp7aWZ7sKWKDinV3KasEQ38lVzt0e5/view","original_SVG":assets["svg_identity"],"pixels_viewed_independently":True,"view_image_detail":"original","official_drive_raw_fetch":"download_raw_file:true include_base64:false; materialized authenticated file_uri independently into own evidence directory","independent_three_download_HTTP_status":200,"reference_SHA256":"9a29fbdc7dd908017924bed270e8dfe18351519eed3fa7bc7001789f2a383414","image_guide_is_not_final":True,"stored_aesthetic_result":"CONTENT_TRANSFER_PASS_WITH_LIMITATIONS","stored_professional_result":"PASS_FOR_IMPLEMENTATION_PROTOCOL_DELIVERY_ONLY"},
 "live_Figma":{"file_key":"uyDxOoN1iNDPpEHTKSUWg1","page":"412:2","frame":"453:10","wordmark":"453:37","canonical_url":"https://www.figma.com/design/uyDxOoN1iNDPpEHTKSUWg1/?node-id=453-10","frame_dimensions":[source["frame"]["width"],source["frame"]["height"]],"total_nodes":source["node_count"],"native_TEXT_count":len(source["texts"]),"native_TEXT_editable":all(not t["locked"] and not t["hasMissingFont"]for t in source["texts"]),"wordmark_VECTOR_count":len(wordmark_vectors),"total_VECTOR_count":len(source["vectors"]),"wordmark_structure":"5 cream compound opacity tiers +4 orange VECTOR paths, editable curves; not native text and not14 independent strokes","wordmark_native_TEXT_count":0,"image_paints_present_in_S7":source["sourceContainsImage"],"font_availability":fonts,"protected_V29_page":"251:2","protected_V29_frame":"402:2","protected_photo":"402:3","protected_photo_observed_subset_matches_saved_S7_proof":photo_match,"protected_photo_image_hash":photo["photo"]["fills"][0]["imageHash"],"protected_photo_image_size":photo["imageSize"],"old_study_transfer_frames_observed_present":source["preserved_page_frames"],"created_node_ids":[],"mutated_node_ids":[],"limits":["Source properties and current fonts were read; no new export, typography change, complete hidden-metadata proof or full historical fingerprint rerun.","Photo node fills/identity/visible/locked/relative transform match saved S7 protection subset; original photo bytes were not independently re-fetched in this task."]},
 "source_input_recovery":{"drive_id":"1QPaUkMUZZ8VJOs1ab8A3RqG89KBW8THq","drive_url":"https://drive.google.com/file/d/1QPaUkMUZZ8VJOs1ab8A3RqG89KBW8THq/view","ZIP_sha256":zipdata["archive_sha256"],"ZIP_bytes":51692,"member_count":zipdata["member_count"],"member_names_and_hashes_match_SOURCE":True,"member_CRC_verified_by_independent_zip_read":True,"all_11_restored_to_own_private_directory":True,"binary_input_count":6,"build_or_trace_executed":False},
 "methods_and_dependencies":{"method_source":"METHODS_AND_REUSE_S7.md; guide-adapter-s7/SOURCE.json DEPENDENCIES.json REUSE_METHOD.json HANDOFF.md","canonical_builder":"build-wordmark-pixel-grid.py","rebuild_recipe":"Restore all11 SOURCE-bound inputs first, then use --root <checkout> --output-dir <restored-folder>; fixed exact unit-cell paths, one tier intersection, solid difference. Do not run historical failed polygon builder.","input_source_description":"264 actual8x8 JPEG donor tiles mapped deterministically to fixed opacity tiers; original print alpha UNKNOWN","mature_dependencies_declared":{"VTracer":"0.6.15 historical failed traces only; not used in final conversion","skia_pathops":"0.9.2 unchanged","sharp":"0.35.4 current bundle metadata","Python":"bundled CPython with Pillow/numpy","fonts":"Six current Figma family/style combinations verified available"},"same_machine_dependency_paths_exist":{k:v["exists"]for k,v in assets["dependency_existence"].items()},"dependency_evidence":assets["dependency_existence"],"clean_machine_install_or_build":"NOT_EXECUTED","known_limits":["Diagnostic render-alpha/check-final-pixels scripts retain original private output paths.","render-preview.cjs contains current bundled absolute sharp path; discover/rebind on another machine.","Saved upstream/wheel/hash evidence is integrity evidence; registry origin or a new-machine installation is not reauthenticated here."]},
 "actual_plugin":{"name":plugin["site"]["title"],"private_site_status":plugin["site"]["status"],"version":plugin["version"]["version_number"],"source_commit":plugin["version"]["source"]["commit_sha"],"deployment_status":plugin["deployment"]["status"],"canonical_url":plugin["site"]["current_live_url"],"mcp_url":plugin["site"]["mcp_connection"]["mcp_url"],"plugin_id":plugin["site"]["mcp_connection"]["plugin_id"],"access_mode":plugin["site"]["access_mode"],"allowlisted_account_count":plugin["site"]["allowed_account_user_count"],"allowed_group_count":plugin["site"]["allowed_group_count"],"external_visitor_count":plugin["site"]["external_visitor_count"],"automation_count":plugin["site"]["automations_count"],"all15_local_source_provenance_hashes_match":all(r["matches"]for r in assets["plugin_source_byte_bindings"]),"actual_unauthenticated_GET_mcp_HTTP_status":401,"installation_or_connection":"NOT_VERIFIED","production_feedback_persistence":"NOT_EXECUTED_NOT_VERIFIED","current_session_custom_tools_exposed":[],"scope":"Experimental0.1.0 project wrapper; get_current_workflow/read-plan and artwork-bound nonauthoritative feedback intake. Separate image/Figma/Drive/reviewer/native writer tools required.","this_reader_installed_connected_or_published":False,"permission_changes":0,"feedback_writes":0},
 "not_verified":["GitHub publication/readback of the current349/371 state; pending separate fixed-SHA stage","Full native validator and test suites; deliberately not repeated while sole writer checks","Rebuild or new tracing; restored input bytes only","New-machine installation, recreation or authoring","Human acceptance, whole-system completion, second-style generalization, time saving or model training","OAuth/plugin connection and durable production feedback"],
 "recovery_blockers":{"saved_S7_artifact_source_and_input_reuse":None,"plugin_connected_execution":"HTTP401 on unauthenticated MCP GET; actual connected tool call not available","expected_public_fresh_entry_receipt":"MISSING_AT_INITIAL_SNAPSHOT; current report exists privately and must be copied/bound by Root before any published recovery claim"},
 "actual_actions":{"business_state_writes":0,"generations":0,"rebuilds":0,"traces":0,"Figma_canvas_mutations":0,"Drive_uploads":0,"Git_commits_or_pushes":0,"messages_to_other_tasks_or_people":0,"automations_created_or_resumed":0,"plugin_feedback_writes":0,"all_writes_inside":".liu-visual-private/s7_fresh_entry"},
 "minor_execution_failures_preserved":[{"failure":"Three first sandbox downloads raised HttpRequestException","resolution":"Narrow read-only escalation succeeded HTTP200 on the same observed official raw file_uri; no URL guessing."},{"failure":"Initial /mcp request used invalid -PassThru option and did not make an HTTP observation","resolution":"Corrected read-only GET returned actual401."},{"failure":"Initial dependency path probe used guessed bundled numpy subdirectory","resolution":"Resolved actual numpy path with stdlib importlib.find_spec; current exists:true, no new installation."}],
 "adaptive_router":{"version_check":"MAINTENANCE_REQUIRED","observed_reasons":["codex_version_changed","model_or_effort_changed","desktop_version_changed"],"router_version":"1.0.0","new_delegation_or_router_update":False,"scope_note":"Read-only narrow recovery continued with current exposed tools; no global maintenance or capability upgrade is claimed."},
 "publication_sanitization":{"ephemeral_download_urls":"REMOVED","canonical_urls_and_file_ids":"RETAINED","sanitized_tool_evidence_not_provider_raw_byte_equivalence":True,"public_binary_originals_not_to_be_committed":True},
 "evidence_files":evidence,
 "continual_learning":{"lightweight_check_completed":True,"refinement_not_triggered":"Known entry/LF invariants were reconfirmed; temporary request/path errors do not qualify as long-term learning; no Skill or business state writes."}
}
(out/"FRESH_ENTRY_REPORT.json").write_text(json.dumps(result,ensure_ascii=False,indent=2)+"\n",encoding="utf-8")
print(json.dumps({"report":str(out/"FRESH_ENTRY_REPORT.json"),"report_exists":True,"report_sha256":sha(out/"FRESH_ENTRY_REPORT.json"),"result":result["result"],"scope":result["scope"],"seal_status":result["seal_status"],"wordmark_vectors":len(wordmark_vectors),"TEXT":len(source["texts"]),"protected_photo_subset_all_match":all(photo_match.values()),"source_input_members":zipdata["member_count"],"plugin_connection":"NOT_VERIFIED_HTTP401"},ensure_ascii=False))

