import json,hashlib,copy,subprocess
from pathlib import Path
R=Path('.');D=json.loads(Path('/tmp/payload.json').read_text());L=R/'continuity/vpd/CURRENT_TASK_LOCK.json';C=R/'continuity/vpd/LATEST_CHECKPOINT.json';A=R/'PROJECT_CONTROL_ADAPTER.json';G=R/'continuity/vpd/state_ledger/commercial_design_pipeline.jsonl';V=R/'visual_memory/vpd_p6_composition_state.py'
S='VPD_P3_PAIR2_CORRECTED_COMPLETE_POSTER_BLIND_PACKAGE_READY_WAITING_EVALUATOR_VERDICT';N='RUN_PAIR2_CORRECTED_COMPLETE_POSTER_INDEPENDENT_BLIND_EVALUATION_AND_RETURN_VERDICT';T='2026-09-24T12:58:00Z'
H=lambda x:hashlib.sha256(x.encode()).hexdigest(); J=lambda o:json.dumps(o,ensure_ascii=False,indent=2)+'\n'
l=json.loads(D['lock']);c=json.loads(D['cp']);a=json.loads(D['ad']);p=l['pair2_equal_budget_figma_ab'];ps=H(D['pkg']);ms=H(D['map']);hs=H(D['hand'])
l.update(revision=136,preserved_prior_revision={'revision':135,'git_blob_sha':D['lockBlob'],'note':'Revision 135 completed the single symmetric correction and closed further correction budget.'},current_stage='Pair2 corrected complete-poster blind package frozen from byte-verified corrected Library assets; X=A/Y=B mapping remains hidden until verdict; frozen evaluator prompt reused unchanged; no Figma/export/Library/evaluation action in this step.',status=S,next_required_action=N,updated_at=T,input_commit='71544883ddde352061c2e83620da28c48f8aa8bc',render_allowed=False,p6_allowed=False)
l['completed_this_revision']=['froze corrected complete-poster blind package','froze corrected mapping X=A/Y=B hidden until verdict','prepared corrected fresh-chat handoff using exact frozen evaluator prompt','preserved correction A=1/B=1 authorization=0 no-second-correction']
p=l['pair2_equal_budget_figma_ab'];p.update(status='CORRECTED_COMPLETE_POSTER_BLIND_PACKAGE_READY',next=N,current_canvas_write_authorization=0,correction_passes_used={'A':1,'B':1},second_aesthetic_correction_allowed=False,corrected_blind_package={'path':'evidence/vpd/library_native_ab_v2/PAIR2_CORRECTED_COMPLETE_POSTER_BLIND_PACKAGE_20260924.json','sha256':ps},corrected_blind_mapping={'path':'evidence/vpd/library_native_ab_v2/PAIR2_CORRECTED_COMPLETE_POSTER_BLIND_MAPPING_20260924.json','sha256':ms},corrected_blind_handoff={'path':'evidence/vpd/library_native_ab_v2/COPY_PAIR2_CORRECTED_COMPLETE_POSTER_BLIND_TO_FRESH_CHAT_20260924.txt','sha256':hs},corrected_complete_poster_blind_verdict='PENDING')
L.write_text(J(l),encoding='utf8');ls=H(L.read_text(encoding='utf8'));c.update(sequence=157,recorded_at=T,current_focus='Pair2 corrected complete-poster blind package ready; mapping hidden; frozen evaluator prompt unchanged.',current_stage=l['current_stage'],status=S,next_required_action=N,updated_at=T,task_lock={'path':'continuity/vpd/CURRENT_TASK_LOCK.json','sha256':ls},pair2_equal_budget_figma_ab=copy.deepcopy(p),pair2_corrected_complete_poster_blind_package=p['corrected_blind_package'],pair2_corrected_complete_poster_blind_mapping=p['corrected_blind_mapping'],pair2_corrected_complete_poster_blind_handoff=p['corrected_blind_handoff']);a['task_lock'].update(revision=136,sha256=ls);a['vpd_system_goal_authority'].update(checkpoint=S,next_required_action=N,render_allowed=False)
lines=D['ledger'].rstrip().splitlines();prev=json.loads(lines[-1]);e={'schema_version':'upcp-state-ledger-event/v1','stream_id':'commercial_design_pipeline','event_id':'EVT-VPD-P3-PAIR2-CORRECTED-BLIND-PACKAGE-READY-20260924-001','event_type':'PAIR2_CORRECTED_COMPLETE_POSTER_BLIND_PACKAGE_READY','project_id':'visual-aesthetic-vpd','task_id':'VPD-SYSTEM-LEVEL-HOLDOUT-TRANSFER-VALIDATION-V1','recorded_at':T,'previous_event_id':prev['event_id'],'previous_event_hash':prev['event_hash'],'lock_sha256':ls,'material':True,'before':{'lock_revision':135,'checkpoint_sequence':156},'after':{'lock_revision':136,'checkpoint_sequence':157,'status':S,'next':N,'correction_passes_used':{'A':1,'B':1},'current_canvas_write_authorization':0},'evidence':[p['corrected_blind_package']['path'],p['corrected_blind_mapping']['path'],p['corrected_blind_handoff']['path']],'reason':'Freeze corrected blind package without changing Figma, exports, Library bytes, or evaluator criteria.'};e['event_hash']=hashlib.sha256(json.dumps(e,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest();G.write_text('\n'.join(lines+[json.dumps(e,ensure_ascii=False,separators=(',',':'))])+'\n',encoding='utf8');c['ledger_tails']={'commercial_design_pipeline':{'event_id':e['event_id'],'event_hash':e['event_hash']}};a['ledger_tails']=copy.deepcopy(c['ledger_tails']);C.write_text(J(c),encoding='utf8');A.write_text(J(a),encoding='utf8')
x=D['py'].replace('PAIR2_CORRECTION_COMPLETE_ACTION = "PREPARE_PAIR2_CORRECTED_COMPLETE_POSTER_BLIND_REVIEW_PACKAGE_NO_CANVAS_WRITE"','PAIR2_CORRECTION_COMPLETE_ACTION = "PREPARE_PAIR2_CORRECTED_COMPLETE_POSTER_BLIND_REVIEW_PACKAGE_NO_CANVAS_WRITE"\nPAIR2_CORRECTED_BLIND_ACTION = "RUN_PAIR2_CORRECTED_COMPLETE_POSTER_INDEPENDENT_BLIND_EVALUATION_AND_RETURN_VERDICT"',1).replace('    PAIR2_CORRECTION_COMPLETE_ACTION,\n}','    PAIR2_CORRECTION_COMPLETE_ACTION,\n    PAIR2_CORRECTED_BLIND_ACTION,\n}',1)
fn='''\n\ndef _validate_pair2_corrected_blind_package(root, lock, cp):\n    pair=lock.get("pair2_equal_budget_figma_ab",{})\n    require(lock.get("status")=="VPD_P3_PAIR2_CORRECTED_COMPLETE_POSTER_BLIND_PACKAGE_READY_WAITING_EVALUATOR_VERDICT","PAIR2_CORRECTED_BLIND_STATE")\n    require(cp.get("pair2_equal_budget_figma_ab")==pair,"PAIR2_CORRECTED_BLIND_CP")\n    require(pair.get("current_canvas_write_authorization")==0 and pair.get("correction_passes_used")=={"A":1,"B":1},"PAIR2_CORRECTED_BLIND_BUDGET")\n    require(pair.get("second_aesthetic_correction_allowed") is False,"PAIR2_CORRECTED_SECOND_CORRECTION")\n    for name in ("corrected_blind_package","corrected_blind_mapping","corrected_blind_handoff","blind_evaluator_prompt"): check_ref(root,pair[name])\n    package=read(root,pair["corrected_blind_package"]["path"]); mapping=read(root,pair["corrected_blind_mapping"]["path"])\n    require(package["status"]=="READY_FOR_INDEPENDENT_BLIND_EVALUATION" and package["no_canvas_write_this_step"] is True,"PAIR2_CORRECTED_PACKAGE")\n    require(package["library_assets"]["X"]["sha256"]=="4b38ab9f7bf61a868e12e71c93603a9fcadd37d79285dca868e1c1f6682498f5" and package["library_assets"]["Y"]["sha256"]=="a84de786f4d9700c0466f3f2a96308a81febf133b73f2d3ff4e1dae1117f9912","PAIR2_CORRECTED_HASH")\n    require(mapping["blind_X"]["route"]=="A" and mapping["blind_Y"]["route"]=="B" and mapping["evaluator_must_not_know_mapping"] is True,"PAIR2_CORRECTED_MAPPING")\n    require(pair["blind_evaluator_prompt"]["sha256"]=="85245627d267d49893c8c0d888c50aea14891e13b14920c46f76ff44705edcf6","PAIR2_CORRECTED_PROMPT")\n    require(lock.get("p6_allowed") is False and lock.get("render_allowed") is False,"PAIR2_CORRECTED_PREMATURE_OPEN")\n'''
x=x.replace('\n\ndef validate_p6_composition_state(root):',fn+'\n\ndef validate_p6_composition_state(root):',1).replace('    if action == PAIR2_CORRECTION_COMPLETE_ACTION:\n        _validate_pair2_symmetric_correction_complete(root, lock, cp)\n','    if action == PAIR2_CORRECTION_COMPLETE_ACTION:\n        _validate_pair2_symmetric_correction_complete(root, lock, cp)\n    if action == PAIR2_CORRECTED_BLIND_ACTION:\n        _validate_pair2_corrected_blind_package(root, lock, cp)\n',1);V.write_text(x,encoding='utf8')
subprocess.run(['python','scripts/verify_visual_memory.py','--vpd-state','--status-card'],check=True)
subprocess.run(['git','rm','-f','scripts/pair2_pkg_once.py','.github/workflows/pair2-pkg-once.yml'],check=True);subprocess.run(['git','add','PROJECT_CONTROL_ADAPTER.json','continuity/vpd','visual_memory/vpd_p6_composition_state.py','evidence/vpd/library_native_ab_v2'],check=True);subprocess.run(['git','config','user.name','github-actions[bot]']);subprocess.run(['git','config','user.email','41898282+github-actions[bot]@users.noreply.github.com']);subprocess.run(['git','commit','--amend','-m','Prepare Pair2 corrected blind review package'],check=True);subprocess.run(['git','push','--force-with-lease','origin','HEAD:visual-program-distillation-v2-photography-design-20260814'],check=True)
