#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json,subprocess
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
NOW='2026-09-14T01:33:00Z'
LOCK=ROOT/'continuity/vpd/CURRENT_TASK_LOCK.json'; CP=ROOT/'continuity/vpd/LATEST_CHECKPOINT.json'; ADAPTER=ROOT/'PROJECT_CONTROL_ADAPTER.json'; LEDGER=ROOT/'continuity/vpd/state_ledger/system_validation.jsonl'
RECEIPT_REL='evidence/vpd/figma_upload_relay/receipts/P6-DOUFANG-B-EXACT-SOURCE-SCRATCH-20260914-01.json'
EVIDENCE_REL='evidence/vpd/p6_authority_repair_v1/DOUFANG_B_EXACT_SOURCE_SCRATCH_DIAGNOSIS_20260914.json'
STATUS='VPD_P6_RELAY_UPLOAD_PASS_PLACEMENT_MISMATCH_BLOCKED'; ACTION='RESOLVE_P6_RELAY_PLACEMENT_MISMATCH_NO_REUPLOAD'
REV28_BLOB='fac9f6cec5a7b861b2962d3d77534108f15f1f69'
SOURCE_SHA='78137a59779a37f08b4df3aef23164d115cc61afb443610b6f6eb066e99671d9'; BAD_HASH='23926508e3fc10dd61e9df883e018e721cb7cc1f'; PRIOR_SCRATCH_HASH='1c9cbf9a9fe1017a3f44eeed563562db8222c889'
def read(p):return json.loads(p.read_text(encoding='utf-8'))
def write(p,o):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
def digest(p):return hashlib.sha256(p.read_bytes().replace(b'\r\n',b'\n')).hexdigest()
def eh(e):return hashlib.sha256(json.dumps(e,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def main():
 l,c,a=read(LOCK),read(CP),read(ADAPTER); r=read(ROOT/RECEIPT_REL)
 assert l['revision']==28 and c['sequence']==50 and l['status']==c['status']==STATUS and l['next_required_action']==c['next_required_action']==ACTION
 assert r['status']=='UPLOAD_PASS' and r['http_status']=='200' and r['node_id']=='44:3' and r['source_sha256']==SOURCE_SHA and r['response']['imageHash']==BAD_HASH
 ev={'schema_version':'vpd-p6-exact-source-scratch-diagnosis/v1','status':'EXACT_SOURCE_FAILS_ON_KNOWN_GOOD_SCRATCH_TARGET','scope':'DIAGNOSTIC_ONLY_NO_FORMAL_NODE_WRITE','figma_file_key':'uyDxOoN1iNDPpEHTKSUWg1','source':{'sha256':SOURCE_SHA,'bytes':422265,'format':'JPEG','mode':'RGB','dimensions':[1152,1536],'jfif_version':[1,1],'icc_profile':'sRGB Google Inc. 2016','icc_profile_bytes':456},'receipt':{'path':RECEIPT_REL,'sha256':digest(ROOT/RECEIPT_REL),'status':'UPLOAD_PASS','http_status':200,'returned_imageHash':BAD_HASH},'scratch_readback':{'node_id':'44:3','parent_frame_id':'44:2','locked':False,'fill_type':'IMAGE','scale_mode':'FILL','observed_imageHash':PRIOR_SCRATCH_HASH,'returned_hash_present_in_image_store':False},'control_comparison':{'doufang_A_source_sha256':'45943cf0b0d04e11e19694a6b1e04cf6fcf29a9b97832ee93bdf2f08d0c57909','doufang_A_container_observed':'JPEG RGB 1152x1536 JFIF1.1 sRGB Google Inc. 2016 ICC 456 bytes','doufang_B_container_observed':'JPEG RGB 1152x1536 JFIF1.1 sRGB Google Inc. 2016 ICC 456 bytes','generic_jpeg_dimension_icc_explanation_supported':False},'established':['The exact frozen Doufang B source fails placement on both formal node 12:12 and known-good nested scratch node 44:3 while transport returns HTTP 200 and the identical imageHash.','The same scratch node successfully commits a small PNG through the same relay, secret, Figma file and nested-node structure.','Generic formal-node, page, nesting, relay, secret, JPEG format, dimensions and ICC explanations are not supported by current evidence.','The failure is narrowed to the Doufang B original-byte/content-hash path or a Figma backend state associated with imageHash 23926508... .'],'next_diagnostic':'RUN_PIXEL_EQUIVALENT_LOSSLESS_PNG_TRANSCODE_OF_FROZEN_DOUFANG_B_TO_SCRATCH_ONLY','recorded_at':NOW}
 write(ROOT/EVIDENCE_REL,ev); evsha=digest(ROOT/EVIDENCE_REL)
 l['revision']=29;l['preserved_prior_revision']={'revision':28,'git_blob_sha':REV28_BLOB,'note':'Revision 28 closed the consumed formal retry and required exact-source scratch diagnosis.'};l['current_stage']='Exact frozen Doufang B bytes were uploaded to known-good scratch node 44:3 and reproduced the formal failure: HTTP 200 / UPLOAD_PASS returned the same imageHash 23926508..., but that hash remained absent from the Figma file image store and the scratch node retained its previous valid fill. Formal node 12:12 is therefore not the cause. Doufang A and B share the same JPEG/RGB/1152x1536/JFIF1.1/sRGB ICC container characteristics, so the remaining suspect is the original-byte/content-hash path or backend state associated with the Doufang B hash. No formal reupload is authorized.';l['completed_this_revision']=['uploaded exact frozen Doufang B source to isolated known-good scratch target only','reproduced imageHash 23926508... with HTTP 200 / UPLOAD_PASS','verified returned hash absent from current file image store and scratch target unchanged','ruled out formal node 12:12 and generic nesting as causes','compared successful Doufang A and failing Doufang B container metadata and found matching JPEG/RGB/dimensions/JFIF/sRGB ICC characteristics'];l['updated_at']=NOW;l['input_commit']=subprocess.check_output(['git','rev-parse','HEAD'],cwd=ROOT,text=True).strip();l['diagnostic_next_required_action']='RUN_PIXEL_EQUIVALENT_LOSSLESS_PNG_TRANSCODE_OF_FROZEN_DOUFANG_B_TO_SCRATCH_ONLY';l['exact_source_scratch_diagnosis']={'path':EVIDENCE_REL,'sha256':evsha};write(LOCK,l);locksha=digest(LOCK)
 c['sequence']=51;c['recorded_at']=NOW;c['current_focus']=l['current_stage'];
 if 'p6_exact_frozen_doufang_B_source_scratch_reproduced_failure' not in c['completed']:c['completed'].append('p6_exact_frozen_doufang_B_source_scratch_reproduced_failure')
 c['status']=STATUS;c['next_required_action']=ACTION;c['task_lock']={'path':'continuity/vpd/CURRENT_TASK_LOCK.json','sha256':locksha};c['blocked']=list(l['blockers']);c['relay']['status']='UPLOAD_PASS_PLACEMENT_MISMATCH_BLOCKED'
 a['task_lock']['revision']=29;a['task_lock']['sha256']=locksha;a['vpd_system_goal_authority']['checkpoint']=STATUS;a['vpd_system_goal_authority']['next_required_action']=ACTION
 raw=LEDGER.read_bytes();prev=json.loads(raw.splitlines()[-1]);assert prev['event_id']==c['ledger_tails']['system_validation']['event_id'] and prev['event_hash']==c['ledger_tails']['system_validation']['event_hash'];e={'schema_version':'upcp-state-ledger-event/v1','event_id':'EVT-VPD-P6-EXACT-SOURCE-SCRATCH-FAIL-20260914-001','event_type':'P6_EXACT_FROZEN_SOURCE_REPRODUCES_PLACEMENT_FAILURE_ON_SCRATCH','stream_id':'system_validation','project_id':'visual-aesthetic-vpd','task_id':'VPD-SYSTEM-LEVEL-HOLDOUT-TRANSFER-VALIDATION-V1','previous_event_id':prev['event_id'],'previous_event_hash':prev['event_hash'],'recorded_at':NOW,'input_remote_head':l['input_commit'],'lock_sha256':locksha,'scope':'SOURCE_OR_CONTENT_HASH_PATH_ISOLATION_NO_FORMAL_REUPLOAD','diagnosis':{'path':EVIDENCE_REL,'sha256':evsha},'next_required_action':ACTION};e['event_hash']=eh(e);raw+=(b'' if raw.endswith(b'\n') else b'\n')+(json.dumps(e,ensure_ascii=False,separators=(',',':'))+'\n').encode();LEDGER.write_bytes(raw);c['ledger_tails']['system_validation']={'event_id':e['event_id'],'event_hash':e['event_hash']};write(CP,c);write(ADAPTER,a)
 assert read(CP)['task_lock']['sha256']==digest(LOCK) and read(ADAPTER)['task_lock']['sha256']==digest(LOCK)
if __name__=='__main__':main()
