#!/usr/bin/env python3
from __future__ import annotations
import hashlib,json,subprocess
from pathlib import Path
R=Path(__file__).resolve().parents[1];NOW='2026-09-14T01:36:00Z';L=R/'continuity/vpd/CURRENT_TASK_LOCK.json';C=R/'continuity/vpd/LATEST_CHECKPOINT.json';A=R/'PROJECT_CONTROL_ADAPTER.json';G=R/'continuity/vpd/state_ledger/system_validation.jsonl'
RR='evidence/vpd/figma_upload_relay/receipts/P6-DOUFANG-B-PIXEL-PNG-PROBE-20260914-01.json';ER='evidence/vpd/p6_authority_repair_v1/DOUFANG_B_PIXEL_EQUIVALENT_PNG_DIAGNOSIS_20260914.json';STATUS='VPD_P6_RELAY_UPLOAD_PASS_PLACEMENT_MISMATCH_BLOCKED';ACTION='RESOLVE_P6_RELAY_PLACEMENT_MISMATCH_NO_REUPLOAD';REV29='1e1308798d6b3da3184a2f23bfbc6f5f72a11c75';OLD='1c9cbf9a9fe1017a3f44eeed563562db8222c889';NEW='196f05569f38a30ac41e06b7aff71304f6309856'
def rd(p):return json.loads(p.read_text(encoding='utf-8'))
def wr(p,o):p.parent.mkdir(parents=True,exist_ok=True);p.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n',encoding='utf-8',newline='\n')
def dg(p):return hashlib.sha256(p.read_bytes().replace(b'\r\n',b'\n')).hexdigest()
def eh(e):return hashlib.sha256(json.dumps(e,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
def main():
 l,c,a=rd(L),rd(C),rd(A);r=rd(R/RR);assert l['revision']==29 and c['sequence']==51 and l['status']==c['status']==STATUS;assert r['status']=='UPLOAD_PASS' and r['http_status']=='200' and r['pixel_equivalence_verified'] is True and r['response']['imageHash']==NEW
 e={'schema_version':'vpd-p6-pixel-equivalent-png-diagnosis/v1','status':'PIXEL_EQUIVALENT_PNG_STILL_FAILS_PLACEMENT','scope':'DIAGNOSTIC_ONLY_NO_FORMAL_WRITE','original_source':{'sha256':r['original_source_sha256'],'content_type':r['original_content_type'],'bytes':r['original_source_size']},'derived_png':{'sha256':r['derived_png_sha256'],'bytes':r['derived_png_size'],'dimensions':r['dimensions'],'mode':r['mode'],'decoded_pixel_sha256':r['decoded_pixel_sha256'],'pixel_equivalence_verified':True},'receipt':{'path':RR,'sha256':dg(R/RR),'http_status':200,'returned_imageHash':NEW},'figma_readback':{'node_id':'44:3','observed_imageHash':OLD,'returned_hash_present_in_image_store':False},'established':['Losslessly re-encoding the exact decoded RGB pixel matrix as PNG changes the transport bytes and returned imageHash but still does not create an observable Figma image-store entry or update the known-good scratch target.','Original JPEG byte encoding, ICC metadata and the single historical imageHash 23926508... are therefore not sufficient explanations.','The unresolved variable is now the full Doufang B pixel content versus current large-image placement behavior.'],'next_diagnostic':'RUN_EXACT_FROZEN_DOUFANG_A_SOURCE_AS_CURRENT_LARGE_IMAGE_SCRATCH_CONTROL','recorded_at':NOW};wr(R/ER,e);es=dg(R/ER)
 l['revision']=30;l['preserved_prior_revision']={'revision':29,'git_blob_sha':REV29,'note':'Revision 29 established exact original Doufang B source failure on a known-good scratch target.'};l['current_stage']='A lossless PNG built from the exact decoded Doufang B RGB pixel matrix also returned HTTP 200 / UPLOAD_PASS but did not enter the Figma file image store or replace scratch node 44:3. This rules out the original JPEG byte encoding, ICC metadata and the single 23926508... hash as sufficient causes. Next diagnostic is a current exact-source Doufang A large-image scratch control; formal 12:12 and Tea A/B remain untouched.';l['completed_this_revision']=['decoded frozen Doufang B JPEG to RGB and losslessly re-encoded the identical pixel matrix as PNG on runner','verified pixel equivalence by decoded-pixel SHA-256','uploaded only the derived PNG to isolated scratch node 44:3','verified HTTP 200 / UPLOAD_PASS returned a new hash 196f0556... but the hash is absent from Image Store and scratch remained unchanged','ruled out original JPEG bytes/ICC/single bad imageHash as sufficient causes'];l['updated_at']=NOW;l['input_commit']=subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip();l['diagnostic_next_required_action']='RUN_EXACT_FROZEN_DOUFANG_A_SOURCE_AS_CURRENT_LARGE_IMAGE_SCRATCH_CONTROL';l['pixel_equivalent_png_diagnosis']={'path':ER,'sha256':es};wr(L,l);ls=dg(L)
 c['sequence']=52;c['recorded_at']=NOW;c['current_focus']=l['current_stage'];
 if 'p6_pixel_equivalent_png_of_doufang_B_still_failed_placement' not in c['completed']:c['completed'].append('p6_pixel_equivalent_png_of_doufang_B_still_failed_placement')
 c['status']=STATUS;c['next_required_action']=ACTION;c['task_lock']={'path':'continuity/vpd/CURRENT_TASK_LOCK.json','sha256':ls};c['blocked']=list(l['blockers']);a['task_lock']['revision']=30;a['task_lock']['sha256']=ls;a['vpd_system_goal_authority']['checkpoint']=STATUS;a['vpd_system_goal_authority']['next_required_action']=ACTION
 raw=G.read_bytes();p=json.loads(raw.splitlines()[-1]);assert p['event_id']==c['ledger_tails']['system_validation']['event_id'] and p['event_hash']==c['ledger_tails']['system_validation']['event_hash'];x={'schema_version':'upcp-state-ledger-event/v1','event_id':'EVT-VPD-P6-PIXEL-PNG-SCRATCH-FAIL-20260914-001','event_type':'P6_PIXEL_EQUIVALENT_PNG_STILL_FAILS_SCRATCH_PLACEMENT','stream_id':'system_validation','project_id':'visual-aesthetic-vpd','task_id':'VPD-SYSTEM-LEVEL-HOLDOUT-TRANSFER-VALIDATION-V1','previous_event_id':p['event_id'],'previous_event_hash':p['event_hash'],'recorded_at':NOW,'input_remote_head':l['input_commit'],'lock_sha256':ls,'scope':'PIXEL_CONTENT_VS_CURRENT_LARGE_IMAGE_PATH_DIAGNOSIS','diagnosis':{'path':ER,'sha256':es},'next_required_action':ACTION};x['event_hash']=eh(x);G.write_bytes(raw+(b'' if raw.endswith(b'\n') else b'\n')+(json.dumps(x,ensure_ascii=False,separators=(',',':'))+'\n').encode());c['ledger_tails']['system_validation']={'event_id':x['event_id'],'event_hash':x['event_hash']};wr(C,c);wr(A,a);assert rd(C)['task_lock']['sha256']==dg(L) and rd(A)['task_lock']['sha256']==dg(L)
if __name__=='__main__':main()
